name: add-issues-to-board

on:
  issues:
    types: [opened, reopened]

jobs:
  add-issues-to-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Board
        uses: monry/actions-add-issue-to-project@v1
        with:
          # Personal Access Token with `repo`, `org:read` and `org:write` granted
          github-token: ${{ secrets.PROJECT_ISSUES_TOKEN_GITHUB }}
          project-owner: "windpioneers"
          project-number: 4
          issue-id: ${{ github.event.issue.node_id }}
