name: add-issues-to-board

on:
  issues:
    types: [opened, reopened]

jobs:
  add-issues-to-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Board
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/windpioneers/projects/4
          github-token: ${{ secrets.PROJECT_ISSUES_TOKEN_GITHUB }}
